version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: akkoma_db
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "akkoma" ]
    env_file: db.env
    volumes:
      - ./postgres:/var/lib/postgresql/data

  web:
    image: akkoma
    container_name: akkoma_web
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider --proxy=off localhost:4000 || exit 1" ]
    restart: always
    ports:
      # Remove this if you're not exposing this to your local network
      - '4000:4000'
    build:
      context: build
      # Feel free to remove or override this section. The variables set below are
      # the current defaults. See 'Build-time variables' in README.md
      args:
        - "UID=911" 
        - "GID=911"
        - "AKKOMA_VER=v3.4.0"
    volumes:
      - ./uploads:/uploads
      - ./static:/static
      - ./config:/config
    env_file: 
      - db.env
    environment:
      DOMAIN: example.com
      INSTANCE_NAME: Akkoma
      ADMIN_EMAIL: admin@example.com
      NOTIFY_EMAIL: notify@example.com
    depends_on:
      - db
